### ISSUE TITLE
每个vim用户都要试一试的GlobalVim--全局vim，在任意编辑环境启用vim模式编辑

### ISSUE THREAD

**Issue by einsxiao** [vim-china/vim-china.org#10]
GlobalVim不仅仅是vim按键绑定，同时支持vim各种模式和常用命令
支持正则替换，寄存器，键盘鼠标广义宏录制

https://ovo.ltd/projects/globalvim/

**Comment by wsdjeg** [comment]
非常不错的一个项目，在 windows 下尝试了一下，效果不错。
