### ISSUE TITLE
关于每一个仓库的维护

### ISSUE THREAD

**Issue by wsdjeg** [vim-china/vim-china.org#2]
在这里，我想先大致说下 vim-china 每一个仓库。

- issues 主要是前期讨论，大家有什么想法都可以在这里开一个 issue 讨论，结论成熟后，根据需要，选择是新建仓库来继续，还是在已有仓库内操作

- hello-vim 这个仓库主要是想收集一些 Vim 学习教程，加以整合。

- plugin-tutor：收集实用插件的配置教程
- vim-script-style-guide：Vim脚本书写规范

**Comment by izhengfan** [comment]
请教一下，如果想分享一些非插件相关的使用技巧，在哪个仓库比较好呢？比如我最近学会利用 Linux 下 fcitx 的接口来自动切换中英文输入法之类的。

**Comment by wsdjeg** [comment]
在 hello-vim 这个仓库吧，这个仓库后面会包括多方面的vim教程.

**Comment by izhengfan** [comment]
好的，谢谢。
