### ISSUE TITLE
关于plugins-tutorial仓库的建议

### ISSUE THREAD

**Issue by floatval** [vim-china/vim-china.org#6]
# 关于各大语言模块化引导的建议

  - 比如受众较广的　**JAVA**,  **C++**, **C#**, **PHP**等 
  可以把这些语言较为常用的插件，比如 **补全** ， **语法检错** , **debug**等。我看这些SPCVim中已经实现的很好了，有点心动

  - 再比如根据开发的性质，比如常见的前后端码农需要的**html标签自动闭合**等等
 ## 以下不涉及建议，是提这个issues的原因。
  当然这样并不意味着要让vim开箱即用。不能和SPCVim的哲学起冲突不是。只是做好一个关于新人的引导。

  起因：某室友在参加过培训回来后，他们老师推荐的编辑器是VIM，但是配置文件却相当的简陋。只设置了基本的行号显示，缩进。语法检错debug等，一点儿没涉及。。。更别说直接在vim中对代码进行编译了。
  
  事后，我向其询问时，答曰vim我已经掌握了啊！故，我觉得我们的交流不能只着眼于顶层，而是应该从底层循序渐进。也是值得高兴的，毕竟vim的受众还是不少的。关键就在于他们愿意学多少，鉴于目前的状况，我认为我们尽量降低vim的门槛，同时引导新人建立正确的观点，可以使得大量的新人留存下来，人的基数够大了，以后我相信vim中国社区一定会是一个非常重要的vim交流学习的地方！
以上

**Comment by wsdjeg** [comment]
我们可以在readme里面对这些语言所涉及到的插件进行分类，然后逐一去写使用和配置教材。有了纲目出来之后，也方便大家参与。

**Comment by wsdjeg** [comment]
有人在群里推荐了两个， Neodebug he  vbuger.vim， 而我自己用的是 vebugger

- https://github.com/cpiger/NeoDebug
- https://github.com/vim-vdebug/vdebug
- https://github.com/idanarye/vim-vebugger

**Comment by izhengfan** [comment]
vim 8.1 发布了，内置了 gdb 支持 （termdebug)

**Comment by izhengfan** [comment]
感觉稍微好点，vim8.1 的 termdebug 会同时开三个窗口： gdb 窗可以运行 gdb 原生命令； IO 窗处理输入输出；源码窗可以和源码交互。

**Comment by floatval** [comment]
@izhengfan 感谢。我去试试。我觉得vim插件越少越好

**Comment by izhengfan** [comment]
添加了一个教程，供参考：

https://github.com/izhengfan/plugins-tutorial/blob/master/termdebug.md

**Comment by wsdjeg** [comment]
好的，感谢

**Comment by wsdjeg** [comment]
讨论转移到邮件组，可以发邮件给 vim-china@googlegroups.com 进行订阅
