### ISSUE TITLE
Vim 周报 01 期

### ISSUE THREAD

**Issue by wsdjeg** [vim-china/vim-china.org#9]
计划定期推送优秀的vim插件、使用技巧文章等内容，欢迎大家推荐。

**Comment by VDeamoV** [comment]
我这边汇总了一个傻瓜式安装vim的方案。不知道可以不。[Github 仓库地址](https://github.com/VDeamoV/VDeamoV-vimrc)

**Comment by wsdjeg** [comment]
@VDeamoV 最好是中文的
